

const data = [
	{
		profilePicture: "assets/pictures/saschafirtina.jpg",
		username: "saschafirtina",
		name: "Sascha Firtina",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
        specialty:"Dentist",
        telephone:780577060,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/marin.ivankovic.jpg",
		username: "marin.ivankovic",
		name: "Marin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dermatorgist",
        telephone:780577061,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/bluemaex.jpg",
		username: "bluemaex",
		name: "Max",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Genecologist",
        telephone:780577062,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/kanyewest.jpg",
		username: "kanyewest",
		name: "ye",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Optharmologist",
        telephone:780577063,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/jxhannamadeleine.jpg",
		username: "Jxhannamadeleine",
		name: " Deleine",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dentist",
        telephone:780577064,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/beyonce.jpg",
		username: "beyonce",
		name: "BeyoncÃ©",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577065,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/nanonkaffeberlin.jpg",
		username: "nanokaffeeberlinXESKD",
		name: "nano kaffee berlin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577066,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
		username: "chapteronecoffeeberlin",
		name: "Chapter One Coffee Berlin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dentist",
        telephone:780577067,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/saschafirtina.jpg",
		username: "saschafirtina-copy",
		name: "Sascha Firtina",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dermatologist",
        telephone:780577067,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/marin.ivankovic.jpg",
		username: "marin.ivankovic-copy",
		name: "Marin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577068,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/bluemaex.jpg",
		username: "bluemaex-copy",
		name: "Max",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dentist",
        telephone:780577069,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/kanyewest.jpg",
		username: "kanyewest-copy",
		name: "ye",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577070,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/jxhannamadeleine.jpg",
		username: "William",
		name: "Kanimba William",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Opthamologists",
        telephone:780577071,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/beyonce.jpg",
		username: "beyonce-copy",
		name: "BeyoncÃ©",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577072,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/nanonkaffeberlin.jpg",
		username: "nanokaffeeberlin",
		name: "nano kaffee berlin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dermatologist",
        telephone:780577073,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/chapteronecoffeeberlin.jpg",
		username: "chapteronecoffeeberlin-copy",
		name: "Chapter One Coffee Berlin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577077,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/saschafirtina.jpg",
		username: "saschafirtina-copy2",
		name: "Sascha Firtina",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Dentist",
        telephone:780577078,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/marin.ivankovic.jpg",
		username: "marin.ivankovic-copy2",
		name: "Marin",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577079,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/bluemaex.jpg",
		username: "bluemaex-copy2",
		name: "Max",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Neurologist",
        telephone:780577080,
		email: "No email in bio",
	},
	{
		profilePicture: "assets/pictures/kanyewest.jpg",
		username: "kanyewest-copy2",
		name: "ye",
        biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum sagittis semper. Fusce maximus purus at leo consequat mattis. Maecenas vel tellus eget risus rhoncus porttitor varius id nisi. Aliquam consectetur, est non aliquam cursus, purus magna pharetra erat, finibus dignissim neque orci et dolor. Curabitur tincidunt purus est, sit amet tincidunt urna condimentum ut. Phasellus a dolor tempor risus ornare faucibus. Etiam gravida tortor enim, ut varius sapien sagittis eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
		specialty:"Pediatrist",
        telephone:780577081,
		email: "No email in bio",
	},
	
];


export function getData() {
  return data;
}